//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gatherings.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GatheringsEntities : DbContext
    {
        public GatheringsEntities()
            : base("name=GatheringsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int ef_CreateEvent(Nullable<System.Guid> i_EventId, string i_ASPNetUsersId, string i_Title, string i_Description, string i_Image, Nullable<System.DateTime> i_StartDate, Nullable<System.DateTime> i_EndDate, Nullable<System.Guid> i_VenueId, Nullable<bool> i_Public)
        {
            var i_EventIdParameter = i_EventId.HasValue ?
                new ObjectParameter("i_EventId", i_EventId) :
                new ObjectParameter("i_EventId", typeof(System.Guid));
    
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            var i_TitleParameter = i_Title != null ?
                new ObjectParameter("i_Title", i_Title) :
                new ObjectParameter("i_Title", typeof(string));
    
            var i_DescriptionParameter = i_Description != null ?
                new ObjectParameter("i_Description", i_Description) :
                new ObjectParameter("i_Description", typeof(string));
    
            var i_ImageParameter = i_Image != null ?
                new ObjectParameter("i_Image", i_Image) :
                new ObjectParameter("i_Image", typeof(string));
    
            var i_StartDateParameter = i_StartDate.HasValue ?
                new ObjectParameter("i_StartDate", i_StartDate) :
                new ObjectParameter("i_StartDate", typeof(System.DateTime));
    
            var i_EndDateParameter = i_EndDate.HasValue ?
                new ObjectParameter("i_EndDate", i_EndDate) :
                new ObjectParameter("i_EndDate", typeof(System.DateTime));
    
            var i_VenueIdParameter = i_VenueId.HasValue ?
                new ObjectParameter("i_VenueId", i_VenueId) :
                new ObjectParameter("i_VenueId", typeof(System.Guid));
    
            var i_PublicParameter = i_Public.HasValue ?
                new ObjectParameter("i_Public", i_Public) :
                new ObjectParameter("i_Public", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_CreateEvent", i_EventIdParameter, i_ASPNetUsersIdParameter, i_TitleParameter, i_DescriptionParameter, i_ImageParameter, i_StartDateParameter, i_EndDateParameter, i_VenueIdParameter, i_PublicParameter);
        }
    
        public virtual int ef_CreateItem(Nullable<System.Guid> i_ItemId, Nullable<System.Guid> i_EventId, Nullable<System.Guid> i_ParentId, string i_Name, string i_Description, Nullable<decimal> i_Price, Nullable<bool> i_Public, string i_CreatedBy)
        {
            var i_ItemIdParameter = i_ItemId.HasValue ?
                new ObjectParameter("i_ItemId", i_ItemId) :
                new ObjectParameter("i_ItemId", typeof(System.Guid));
    
            var i_EventIdParameter = i_EventId.HasValue ?
                new ObjectParameter("i_EventId", i_EventId) :
                new ObjectParameter("i_EventId", typeof(System.Guid));
    
            var i_ParentIdParameter = i_ParentId.HasValue ?
                new ObjectParameter("i_ParentId", i_ParentId) :
                new ObjectParameter("i_ParentId", typeof(System.Guid));
    
            var i_NameParameter = i_Name != null ?
                new ObjectParameter("i_Name", i_Name) :
                new ObjectParameter("i_Name", typeof(string));
    
            var i_DescriptionParameter = i_Description != null ?
                new ObjectParameter("i_Description", i_Description) :
                new ObjectParameter("i_Description", typeof(string));
    
            var i_PriceParameter = i_Price.HasValue ?
                new ObjectParameter("i_Price", i_Price) :
                new ObjectParameter("i_Price", typeof(decimal));
    
            var i_PublicParameter = i_Public.HasValue ?
                new ObjectParameter("i_Public", i_Public) :
                new ObjectParameter("i_Public", typeof(bool));
    
            var i_CreatedByParameter = i_CreatedBy != null ?
                new ObjectParameter("i_CreatedBy", i_CreatedBy) :
                new ObjectParameter("i_CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_CreateItem", i_ItemIdParameter, i_EventIdParameter, i_ParentIdParameter, i_NameParameter, i_DescriptionParameter, i_PriceParameter, i_PublicParameter, i_CreatedByParameter);
        }
    
        public virtual int ef_CreateSponsorship(Nullable<System.Guid> i_SponsorshipId, Nullable<System.Guid> i_ItemId, string i_ASPNetUsersId, Nullable<decimal> i_SponsorshipAmount, Nullable<bool> i_Public)
        {
            var i_SponsorshipIdParameter = i_SponsorshipId.HasValue ?
                new ObjectParameter("i_SponsorshipId", i_SponsorshipId) :
                new ObjectParameter("i_SponsorshipId", typeof(System.Guid));
    
            var i_ItemIdParameter = i_ItemId.HasValue ?
                new ObjectParameter("i_ItemId", i_ItemId) :
                new ObjectParameter("i_ItemId", typeof(System.Guid));
    
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            var i_SponsorshipAmountParameter = i_SponsorshipAmount.HasValue ?
                new ObjectParameter("i_SponsorshipAmount", i_SponsorshipAmount) :
                new ObjectParameter("i_SponsorshipAmount", typeof(decimal));
    
            var i_PublicParameter = i_Public.HasValue ?
                new ObjectParameter("i_Public", i_Public) :
                new ObjectParameter("i_Public", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_CreateSponsorship", i_SponsorshipIdParameter, i_ItemIdParameter, i_ASPNetUsersIdParameter, i_SponsorshipAmountParameter, i_PublicParameter);
        }
    
        public virtual int ef_CreateVenue(Nullable<System.Guid> i_VenueId, string i_ASPNetUsersId, string i_VenueName, Nullable<System.Guid> i_AddressId, string i_Street1, string i_Street2, string i_Street3, string i_Street4, string i_City, string i_State, string i_PostalCode, string i_Country)
        {
            var i_VenueIdParameter = i_VenueId.HasValue ?
                new ObjectParameter("i_VenueId", i_VenueId) :
                new ObjectParameter("i_VenueId", typeof(System.Guid));
    
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            var i_VenueNameParameter = i_VenueName != null ?
                new ObjectParameter("i_VenueName", i_VenueName) :
                new ObjectParameter("i_VenueName", typeof(string));
    
            var i_AddressIdParameter = i_AddressId.HasValue ?
                new ObjectParameter("i_AddressId", i_AddressId) :
                new ObjectParameter("i_AddressId", typeof(System.Guid));
    
            var i_Street1Parameter = i_Street1 != null ?
                new ObjectParameter("i_Street1", i_Street1) :
                new ObjectParameter("i_Street1", typeof(string));
    
            var i_Street2Parameter = i_Street2 != null ?
                new ObjectParameter("i_Street2", i_Street2) :
                new ObjectParameter("i_Street2", typeof(string));
    
            var i_Street3Parameter = i_Street3 != null ?
                new ObjectParameter("i_Street3", i_Street3) :
                new ObjectParameter("i_Street3", typeof(string));
    
            var i_Street4Parameter = i_Street4 != null ?
                new ObjectParameter("i_Street4", i_Street4) :
                new ObjectParameter("i_Street4", typeof(string));
    
            var i_CityParameter = i_City != null ?
                new ObjectParameter("i_City", i_City) :
                new ObjectParameter("i_City", typeof(string));
    
            var i_StateParameter = i_State != null ?
                new ObjectParameter("i_State", i_State) :
                new ObjectParameter("i_State", typeof(string));
    
            var i_PostalCodeParameter = i_PostalCode != null ?
                new ObjectParameter("i_PostalCode", i_PostalCode) :
                new ObjectParameter("i_PostalCode", typeof(string));
    
            var i_CountryParameter = i_Country != null ?
                new ObjectParameter("i_Country", i_Country) :
                new ObjectParameter("i_Country", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_CreateVenue", i_VenueIdParameter, i_ASPNetUsersIdParameter, i_VenueNameParameter, i_AddressIdParameter, i_Street1Parameter, i_Street2Parameter, i_Street3Parameter, i_Street4Parameter, i_CityParameter, i_StateParameter, i_PostalCodeParameter, i_CountryParameter);
        }
    
        public virtual ObjectResult<ef_GetEvent_Result> ef_GetEvent(Nullable<System.Guid> i_EventId, string i_ASPNetUsersId)
        {
            var i_EventIdParameter = i_EventId.HasValue ?
                new ObjectParameter("i_EventId", i_EventId) :
                new ObjectParameter("i_EventId", typeof(System.Guid));
    
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ef_GetEvent_Result>("ef_GetEvent", i_EventIdParameter, i_ASPNetUsersIdParameter);
        }
    
        public virtual ObjectResult<ef_GetItem_Result> ef_GetItem(Nullable<System.Guid> i_ItemId)
        {
            var i_ItemIdParameter = i_ItemId.HasValue ?
                new ObjectParameter("i_ItemId", i_ItemId) :
                new ObjectParameter("i_ItemId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ef_GetItem_Result>("ef_GetItem", i_ItemIdParameter);
        }
    
        public virtual ObjectResult<ef_GetUser_Result> ef_GetUser(string i_ASPNetUsersId)
        {
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ef_GetUser_Result>("ef_GetUser", i_ASPNetUsersIdParameter);
        }
    
        public virtual ObjectResult<ef_GetVenue_Result> ef_GetVenue(string i_ASPNetUsersId, Nullable<System.Guid> i_VenueId)
        {
            var i_ASPNetUsersIdParameter = i_ASPNetUsersId != null ?
                new ObjectParameter("i_ASPNetUsersId", i_ASPNetUsersId) :
                new ObjectParameter("i_ASPNetUsersId", typeof(string));
    
            var i_VenueIdParameter = i_VenueId.HasValue ?
                new ObjectParameter("i_VenueId", i_VenueId) :
                new ObjectParameter("i_VenueId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ef_GetVenue_Result>("ef_GetVenue", i_ASPNetUsersIdParameter, i_VenueIdParameter);
        }
    
        public virtual int ef_UpdateAspNetUser(string i_UserName, string i_Email, string i_PhoneNumber, string i_FullName)
        {
            var i_UserNameParameter = i_UserName != null ?
                new ObjectParameter("i_UserName", i_UserName) :
                new ObjectParameter("i_UserName", typeof(string));
    
            var i_EmailParameter = i_Email != null ?
                new ObjectParameter("i_Email", i_Email) :
                new ObjectParameter("i_Email", typeof(string));
    
            var i_PhoneNumberParameter = i_PhoneNumber != null ?
                new ObjectParameter("i_PhoneNumber", i_PhoneNumber) :
                new ObjectParameter("i_PhoneNumber", typeof(string));
    
            var i_FullNameParameter = i_FullName != null ?
                new ObjectParameter("i_FullName", i_FullName) :
                new ObjectParameter("i_FullName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_UpdateAspNetUser", i_UserNameParameter, i_EmailParameter, i_PhoneNumberParameter, i_FullNameParameter);
        }
    
        public virtual int ef_UpdateEvent(Nullable<System.Guid> i_EventId, string i_Title, string i_Description, string i_Image, Nullable<System.DateTime> i_StartDate, Nullable<System.DateTime> i_EndDate, Nullable<System.Guid> i_VenueId, Nullable<bool> i_Public, Nullable<bool> i_IsDeleted)
        {
            var i_EventIdParameter = i_EventId.HasValue ?
                new ObjectParameter("i_EventId", i_EventId) :
                new ObjectParameter("i_EventId", typeof(System.Guid));
    
            var i_TitleParameter = i_Title != null ?
                new ObjectParameter("i_Title", i_Title) :
                new ObjectParameter("i_Title", typeof(string));
    
            var i_DescriptionParameter = i_Description != null ?
                new ObjectParameter("i_Description", i_Description) :
                new ObjectParameter("i_Description", typeof(string));
    
            var i_ImageParameter = i_Image != null ?
                new ObjectParameter("i_Image", i_Image) :
                new ObjectParameter("i_Image", typeof(string));
    
            var i_StartDateParameter = i_StartDate.HasValue ?
                new ObjectParameter("i_StartDate", i_StartDate) :
                new ObjectParameter("i_StartDate", typeof(System.DateTime));
    
            var i_EndDateParameter = i_EndDate.HasValue ?
                new ObjectParameter("i_EndDate", i_EndDate) :
                new ObjectParameter("i_EndDate", typeof(System.DateTime));
    
            var i_VenueIdParameter = i_VenueId.HasValue ?
                new ObjectParameter("i_VenueId", i_VenueId) :
                new ObjectParameter("i_VenueId", typeof(System.Guid));
    
            var i_PublicParameter = i_Public.HasValue ?
                new ObjectParameter("i_Public", i_Public) :
                new ObjectParameter("i_Public", typeof(bool));
    
            var i_IsDeletedParameter = i_IsDeleted.HasValue ?
                new ObjectParameter("i_IsDeleted", i_IsDeleted) :
                new ObjectParameter("i_IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_UpdateEvent", i_EventIdParameter, i_TitleParameter, i_DescriptionParameter, i_ImageParameter, i_StartDateParameter, i_EndDateParameter, i_VenueIdParameter, i_PublicParameter, i_IsDeletedParameter);
        }
    
        public virtual int ef_UpdateItem(Nullable<System.Guid> i_ItemId, Nullable<System.Guid> i_ParentId, string i_Name, string i_Description, Nullable<decimal> i_Price, Nullable<bool> i_Public, Nullable<bool> i_IsDeleted)
        {
            var i_ItemIdParameter = i_ItemId.HasValue ?
                new ObjectParameter("i_ItemId", i_ItemId) :
                new ObjectParameter("i_ItemId", typeof(System.Guid));
    
            var i_ParentIdParameter = i_ParentId.HasValue ?
                new ObjectParameter("i_ParentId", i_ParentId) :
                new ObjectParameter("i_ParentId", typeof(System.Guid));
    
            var i_NameParameter = i_Name != null ?
                new ObjectParameter("i_Name", i_Name) :
                new ObjectParameter("i_Name", typeof(string));
    
            var i_DescriptionParameter = i_Description != null ?
                new ObjectParameter("i_Description", i_Description) :
                new ObjectParameter("i_Description", typeof(string));
    
            var i_PriceParameter = i_Price.HasValue ?
                new ObjectParameter("i_Price", i_Price) :
                new ObjectParameter("i_Price", typeof(decimal));
    
            var i_PublicParameter = i_Public.HasValue ?
                new ObjectParameter("i_Public", i_Public) :
                new ObjectParameter("i_Public", typeof(bool));
    
            var i_IsDeletedParameter = i_IsDeleted.HasValue ?
                new ObjectParameter("i_IsDeleted", i_IsDeleted) :
                new ObjectParameter("i_IsDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ef_UpdateItem", i_ItemIdParameter, i_ParentIdParameter, i_NameParameter, i_DescriptionParameter, i_PriceParameter, i_PublicParameter, i_IsDeletedParameter);
        }
    }
}
